import {api} from '../assets/api.mjs';import {sendAndConfirm} from '../assets/transactions.mjs';import {createFlow,selectCase,bindPrepared,clearCase,assertFlowPrepared,pruneFlow} from '../assets/decisionDraft.mjs';import {renderShell,tell,el,button,amount,stageLabels} from '../assets/shell.mjs';import {renderTimeline} from './detail.mjs';
export function workerMessage(status){return {running:'正在运行',stopping:'正在停止，等待当前交易',stopped:'已停止',offline:'离线；旧进程锁需核对'}[status.state]??status.state}
async function init(){const {wallet,config,scope,requireWallet}=await renderShell('audit');let polling=false,configured=false;let flow=createFlow();
 function operator(){return wallet.state.authenticated&&wallet.state.address?.toLowerCase()===config.auditor?.toLowerCase()}
 function controls(){for(const id of ['stake','start','stop'])document.querySelector('#'+id).disabled=!operator()||(id==='start'&&!configured);document.querySelector('#auditor-address').textContent=config.auditor??'未配置审计服务钱包'}
 document.addEventListener('wallet-state',controls);controls();
 async function refresh(){if(polling||document.hidden||!config.ready)return;polling=true;try{
  const [status,runs,skills]=await Promise.all([api(scope('/api/agent/status')),api(scope('/api/agent/runs')),api(scope('/api/skills'))]);
  configured=status.configReady===true;controls();document.querySelector('#worker-state').textContent=workerMessage(status);document.querySelector('#agent-config').textContent=configured?'工具调用 Agent · 模型：'+status.model:status.configurationError||'请配置 LLM API';document.querySelector('#worker-source').textContent=status.source?'来源：'+status.source:'等待审计钱包启动';document.querySelector('#stake-state').textContent=status.stakeWei!==undefined?`已质押 ${amount(status.stakeWei)} ${config.nativeSymbol}；缺额 ${amount(status.shortfallWei)} ${config.nativeSymbol}`:status.chainError||'读取质押中…';
  const runlist=document.querySelector('#runs');runlist.replaceChildren();for(const run of runs.slice(0,30)){const row=el('div',undefined,'skill-row');const skill=skills.find(r=>r.key===run.key);const link=el('a',skill?skill.name+' · '+skill.version:run.key,'mono');link.href='/skills/'+run.key;row.append(link,button(stageLabels[run.stage]??run.stage,async()=>{const events=await api(scope('/api/agent/events',{runId:run.runId,after:'0'}));renderTimeline(events,document.querySelector('#timeline'))},'secondary'));runlist.append(row)}
  if(!runs.length)runlist.append(el('p','当前部署尚无 Agent 运行记录。旧结果可从技能详情核对。','muted'));
  const pending=document.querySelector('#decisions');pending.replaceChildren();
  const waitingKeys=[];
  for(const run of runs.filter(r=>r.stage==='waiting_human')){const skill=skills.find(r=>r.key===run.key);if(!skill||skill.status!==2)continue;waitingKeys.push(skill.key);const card=el('div',undefined,'panel');const link=el('a',skill.name+' · 查看真实报告');link.href='/skills/'+skill.key;card.append(link);if(operator())for(const decision of ['safe','malicious'])card.append(button(decision==='safe'?'人工裁决：安全':'人工裁决：恶意',async()=>{flow=selectCase(flow,skill.key);await requireWallet();const prepared=await api('/api/auditor/prepare',{body:{action:'human_decision',key:skill.key,decision}});try{assertFlowPrepared(flow,skill.key,prepared.id)}catch(error){flow=clearCase(flow);await api('/api/auditor/cancel',{body:{preparedId:prepared.id}}).catch(()=>{});tell(error.message,true);await refresh();return}flow=bindPrepared(flow,prepared.id);await sendAndConfirm(prepared,'/api/auditor/confirm',tell);flow=clearCase(flow);await refresh()}));else card.append(el('p','只有审计服务钱包可签名裁决。','muted'));pending.append(card)}
  // 案件不在待裁决列表（被处理 / 部署切换）时立即清空草稿，杜绝上一案残留到下一案
  flow=pruneFlow(flow,waitingKeys);
 }catch(error){tell(error.message,true)}finally{polling=false}}
 document.querySelector('#stake').addEventListener('click',async()=>{try{await requireWallet();const prepared=await api('/api/auditor/prepare',{body:{action:'stake',valueWei:document.querySelector('#stake-wei').value}});await sendAndConfirm(prepared,'/api/auditor/confirm',tell);await refresh()}catch(error){tell(error.message,true)}});
 for(const action of ['start','stop'])document.querySelector('#'+action).addEventListener('click',async()=>{try{await requireWallet();await api('/api/agent/'+action,{body:{}});await refresh()}catch(error){tell(error.message,true)}});
 document.querySelector('#refresh').addEventListener('click',refresh);await refresh();setInterval(refresh,2000);
}
if(typeof window!=='undefined'&&typeof document!=='undefined'&&location.pathname==='/audit')init().catch(error=>tell(error.message,true));
