import {api} from '../assets/api.mjs';import {renderShell,el,tell,statuses,stageLabels} from '../assets/shell.mjs';
export function historyMessage(events,row){return !events.length&&[3,4].includes(row.status)?'已有审计结果，未保存运行日志':!events.length?'尚未保存审计运行记录':''}
export function renderFindings(findings,target){target.replaceChildren?.();for(const finding of findings??[]){const card=el('div',undefined,'panel');card.append(el('strong',(finding.rule??finding.ruleId??'规则')+' · '+(finding.severity??'')),el('p',finding.file??'', 'mono'),el('pre',finding.evidence??''));target.append(card)}}
export function renderTimeline(events,target){target.replaceChildren();for(const event of events){const row=el('div',undefined,'event');const timestamp=el('time',new Date(event.time*1000).toLocaleString());row.append(timestamp,el('strong',stageLabels[event.stage]??event.stage));if(event.stage.startsWith('agent_'))row.append(el('pre',JSON.stringify(event.payload,null,2)));if(event.payload?.txHash)row.append(el('p',event.payload.txHash,'mono'));if(event.payload?.category)row.append(el('p',event.payload.category,'muted'));if(event.payload?.reason)row.append(el('p',event.payload.reason,'muted'));target.append(row)}}
async function init(){const {scope}=await renderShell('detail');const key=location.pathname.split('/').at(-1);const row=await api(scope('/api/skills/'+key));document.querySelector('#skill-name').textContent=row.name;document.querySelector('#skill-version').textContent='v'+row.version+' · '+statuses[row.status];
 const identity=document.querySelector('#identity');for(const [label,value] of [['发布者',row.publisher],['审计者',row.auditor],['内容哈希',row.codeHash],['Manifest 哈希',row.metadataHash],['报告哈希',row.reportHash],['登记交易',row.registrationTx]]){identity.append(el('dt',label),el('dd',value,'mono'))}
 document.querySelector('#license').textContent=row.license?JSON.stringify(row.license,null,2):'此版本尚未铸造许可证。';
 document.querySelector('#files').textContent=row.package?JSON.stringify(row.package,null,2):row.sourceNote||'服务未取得与登记哈希一致的来源。';
 renderTimeline(row.events,document.querySelector('#timeline'));document.querySelector('#history').textContent=row.historyNote||historyMessage(row.events,row);
 const view=row.report??row.pendingReport;document.querySelector('#report-status').textContent=view?view.availability==='present'?(view.reportMatchesChain?'报告哈希与当前链一致':'报告已保存，尚未形成链上结论'):'报告'+(view.availability==='missing'?'缺失':'损坏，无法核对'):'暂无可读报告';
 if(view?.report){const agent=view.report.agent;document.querySelector('#report-status').append(el('p',agent?.complete?`Agent：${agent.model} · ${agent.rounds} 轮 · ${agent.toolCalls} 次工具调用\n${agent.summary}`:'历史规则审计报告：没有模型 Agent 审计记录。'));document.querySelector('#report-json').textContent=JSON.stringify(view.report,null,2);renderFindings(view.report.findings,document.querySelector('#findings'))}
 document.querySelector('#install-link').href='/install?key='+encodeURIComponent(key);
}
if(typeof window!=='undefined'&&typeof document!=='undefined'&&location.pathname.startsWith('/skills/'))init().catch(error=>tell(error.message,true));
