import {api} from '../assets/api.mjs';import {sendAndConfirm} from '../assets/transactions.mjs';import {renderShell,tell,el,skillList,button} from '../assets/shell.mjs';
export async function publishArchive(zip,request=api,send=sendAndConfirm){const preview=await request('/api/packages',{zip});const prepared=await request('/api/publisher/prepare',{body:{action:'register',packageId:preview.packageId}});const result=await send(prepared,'/api/publisher/confirm',tell);return {preview,result}}
export async function requestAudit(key,request=api,send=sendAndConfirm){const prepared=await request('/api/publisher/prepare',{body:{action:'request_audit',key}});return send(prepared,'/api/publisher/confirm',tell)}
async function init(){const {wallet,scope,requireWallet}=await renderShell('publish');let preview=null;
 async function funds(){if(!wallet.state.address){document.querySelector('#funds').textContent='连接钱包后读取可领取余额。';document.querySelector('#withdraw').disabled=true;return}
  try{const data=await api(scope('/api/funds',{address:wallet.state.address}));document.querySelector('#funds').textContent=data.creditsWei==='0'?'没有可领取余额。':'可领取 '+data.creditsWei+' wei。';document.querySelector('#withdraw').disabled=data.creditsWei==='0'}catch(error){document.querySelector('#funds').textContent='无法读取可领取余额。';document.querySelector('#withdraw').disabled=true}}
 document.querySelector('#withdraw').addEventListener('click',async()=>{try{await requireWallet();const prepared=await api('/api/funds/prepare',{body:{action:'withdraw'}});await sendAndConfirm(prepared,'/api/funds/confirm',tell);await funds()}catch(error){tell(error.message,true)}});
 async function mine(){const container=document.querySelector('#mine');container.replaceChildren();if(!wallet.state.address){container.append(el('p','连接发布者钱包后显示我的技能。','muted'));await funds();return}const address=wallet.state.address,generation=wallet.state.generation;try{const rows=await api(scope('/api/skills',{publisher:address}));if(generation!==wallet.state.generation)return;skillList(rows,container);for(const row of rows.filter(r=>r.status===1)){container.append(button('为 '+row.name+' 锁押金并请求审计',async()=>{await requireWallet();await requestAudit(row.key);await mine()}))}for(const row of rows.filter(r=>r.status===5&&r.arbitration&&r.arbitration.deadline*1000<Date.now())){container.append(button('释放 '+row.name+' 已到期押金',async()=>{await requireWallet();const prepared=await api('/api/funds/prepare',{body:{action:'expire',key:row.key}});await sendAndConfirm(prepared,'/api/funds/confirm',tell);await mine();await funds()}))}await funds()}catch(error){tell(error.message,true)}}
 const upload=document.querySelector('#upload');upload.addEventListener('click',async()=>{upload.disabled=true;try{await requireWallet();const file=document.querySelector('#archive').files[0];if(!file)throw Error('请先选择 ZIP 文件');const generation=wallet.state.generation;preview=await api('/api/packages',{zip:file});if(generation!==wallet.state.generation){preview=null;throw Error('钱包已改变，请重新上传')}const view=document.querySelector('#preview');view.replaceChildren(el('h3',preview.manifest.name+' · '+preview.manifest.version),el('pre',JSON.stringify({manifest:preview.manifest,files:preview.files,codeHash:preview.codeHash,metadataHash:preview.metadataHash},null,2)));document.querySelector('#register').disabled=false;tell('已验证 ZIP。核对内容后，用发布者钱包签名登记。')}catch(error){tell(error.message,true)}finally{upload.disabled=false}});
 const register=document.querySelector('#register');register.addEventListener('click',async()=>{register.disabled=true;try{await requireWallet();if(!preview||preview.publisher.toLowerCase()!==wallet.state.address.toLowerCase())throw Error('请重新上传属于当前钱包的 ZIP');const prepared=await api('/api/publisher/prepare',{body:{action:'register',packageId:preview.packageId}});await sendAndConfirm(prepared,'/api/publisher/confirm',tell);await mine()}catch(error){tell(error.message,true)}finally{register.disabled=!preview}});
 document.addEventListener('wallet-state',()=>{preview=null;register.disabled=true;document.querySelector('#preview').replaceChildren();mine()});document.querySelector('#refresh-mine').addEventListener('click',mine);await mine();}
if(typeof document!=='undefined')init().catch(error=>tell(error.message,true));
